# Generated by Django 5.2 on 2025-05-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("company_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("about", models.TextField()),
                (
                    "types",
                    models.CharField(
                        choices=[
                            ("IT", "IT"),
                            ("Non IT", "Non IT"),
                            ("Mobile Phones", "Mobile Phones"),
                        ],
                        max_length=100,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
            ],
        ),
    ]
