# Generated by Django 5.2 on 2025-05-13 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("employee_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("about", models.TextField()),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("Manager", "Manager"),
                            ("Software Developer", "Software Developer"),
                            ("Project Leader", "Project Leader"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.company"
                    ),
                ),
            ],
        ),
    ]
